### ISSUE TITLE
Glide UI library support

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Samples#47]
The UI library is more dynamic but some users may opt for a fixed simple window. Should we support Glide? Or it least provide unsupported?

Make sure to test touch inputs as well.

**Comment by davemclaughlin** [comment]
Glide was superb for making quick interfaces and if we could have something similar, I will vote for it. Somethng along the lines of Glide Studio that Blackdog spare wrote would also be good to allow us to build the interface and save the XML. Most of Glide was ported by one of the beat team some time ago with TinyCLR1.0 but he ran into issues with missing features in TinyCLR that prevented completion of the project. I've tried porting to 2.0 but ran into similar issues.

**Comment by gus-ghielec** [comment]
Improvements were made to UI library, which is superior to glide.
